### ISSUE TITLE
There is a problem with recurrence

### ISSUE THREAD

**Issue by cv-cat** [pramalhe/2PLSF#1]
![Snipaste_2024-02-20_22-56-45](https://github.com/pramalhe/2PLSF/assets/94289429/e11f3787-e275-4152-9837-82a1a73c888d)

In emersion git repository (https://github.com/pramalhe/2PLSF) encountered the following problems in the process of the code, how can I solve?

**Comment by cv-cat** [comment]
Running run-all.py produces the above result, showing that two files are missing, and what should I do if I want to get the graph in my paper?

**Comment by pramalhe** [comment]
Hello,
The two targets (map-ziptree-2plundo and map-ziptree2plundodist) are not needed for any of the plots.
After the run-all.py completes, the data will be in the graphs/data/\*.txt folder and you can run the shell script graphs/plots/plot-all.sh to generate the .pdf from the data in the graphs/data/\*.txt
You will need eps2pdf and gnuplot if you want to generate the plots, otherwise just look at the \*.txt files and compare them numerically.
